# .github/workflows/post-to-x.yml

name: Post Latest News to X

# Run every hour, on the hour (UTC)
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  post_to_x:
    runs-on: ubuntu-latest

    steps:
      - name: Post a tweet linking to your site
        env:
          BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          # Customize this however you want (emoji, wording, etc.)
          MESSAGE="⚽ Stay up-to-date: https://toc89.github.io/football-news-site/"

          # Send the post via the X (Twitter) API v2
          curl -X POST "https://api.twitter.com/2/tweets" \
            -H "Authorization: Bearer $BEARER_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"$MESSAGE\"}"
