name: Post Latest News to X

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  post_to_x:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Twitter library
        run: |
          npm init -y
          npm install twitter-api-v2

      - name: Post Latest News to X
        env:
          TW_CONSUMER_KEY:    ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN:    ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET:   ${{ secrets.TW_ACCESS_SECRET }}
          NEWS_API_KEY:       ${{ secrets.NEWS_API_KEY }}
        run: |
          node -e "
            const { TwitterApi } = require('twitter-api-v2');
            const client = new TwitterApi({
              appKey: process.env.TW_CONSUMER_KEY,
              appSecret: process.env.TW_CONSUMER_SECRET,
              accessToken: process.env.TW_ACCESS_TOKEN,
              accessSecret: process.env.TW_ACCESS_SECRET,
            });
            (async () => {
              const headline = 'Stay up-to-date: https://toc89.github.io/football-news-site/';
              const { data } = await client.v2.tweet(headline);
              console.log('✅ Tweet sent, ID:', data.id);
            })();
          "
